FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build

COPY greetings/*.csproj /greetings/

COPY greetings/. /greetings/
WORKDIR /greetings
RUN dotnet restore
RUN dotnet publish greetings.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
WORKDIR /app
COPY --from=build /greetings/out ./

EXPOSE 80
EXPOSE 443

ENTRYPOINT ["dotnet", "greetings.dll"]