FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build

COPY friends/*.csproj /friends/

COPY friends/. /friends/
WORKDIR /friends
RUN dotnet restore
RUN dotnet publish friends.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
WORKDIR /app
COPY --from=build /friends/out ./

EXPOSE 80
EXPOSE 443

ENTRYPOINT ["dotnet", "friends.dll"]